export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  safelist: [
    'bg-card-blue',
    'bg-card-orange',
    'bg-card-red',
    'bg-card-yellow',
    'bg-card-green',
    'bg-card-blue-secondary',
    'bg-card-orange-secondary',
    'bg-card-red-secondary',
    'bg-card-yellow-secondary',
    'bg-card-green-secondary',
    'border-card-blue-border',
    'border-card-orange-border',
    'border-card-red-border',
    'border-card-yellow-border',
    'border-card-green-border',
    'text-card-text-secondary',
  ],
  theme: {
    extend: {
      colors: {
        background: "rgba(var(--background))",
        border: "rgba(var(--border))",
        card: "rgba(var(--card))",
        "card-secondary": "rgba(var(--card-secondary))",
        theme: "rgba(var(--theme))",
        "theme-text": "rgba(var(--theme-text))",
        "card-blue": "rgba(var(--card-blue))",
        "card-orange": "rgba(var(--card-orange))",
        "card-red": "rgba(var(--card-red))",
        "card-yellow": "rgba(var(--card-yellow))",
        "card-green": "rgba(var(--card-green))",
        "card-blue-secondary": "rgba(var(--card-blue-secondary))",
        "card-orange-secondary": "rgba(var(--card-orange-secondary))",
        "card-red-secondary": "rgba(var(--card-red-secondary))",
        "card-yellow-secondary": "rgba(var(--card-yellow-secondary))",
        "card-green-secondary": "rgba(var(--card-green-secondary))",
        "card-blue-border": "rgba(var(--card-blue-border))",
        "card-orange-border": "rgba(var(--card-orange-border))",
        "card-red-border": "rgba(var(--card-red-border))",
        "card-yellow-border": "rgba(var(--card-yellow-border))",
        "card-green-border": "rgba(var(--card-green-border))",
        "card-text": "rgba(var(--card-text))",
        "card-text-secondary": "rgba(var(--card-text-secondary))",
        "copy-primary": "rgba(var(--copy-primary))",
        "copy-secondary": "rgba(var(--copy-secondary))",
      },
    },
  },
  plugins: [],
}